// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/Message.proto

package com.geek.rpc.message;

public final class ProtoBufMessage {
  private ProtoBufMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MessageRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>uint64 message_id = 1;</code>
     */
    long getMessageId();

    /**
     * <pre>
     *发送方信息
     * </pre>
     *
     * <code>string message_from = 2;</code>
     */
    java.lang.String getMessageFrom();
    /**
     * <pre>
     *发送方信息
     * </pre>
     *
     * <code>string message_from = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageFromBytes();

    /**
     * <pre>
     *时间戳(单位:毫秒)
     * </pre>
     *
     * <code>uint64 time = 3;</code>
     */
    long getTime();

    /**
     * <pre>
     *消息类型  1：纯文本  2：其他
     * </pre>
     *
     * <code>uint32 msg_type = 4;</code>
     */
    int getMsgType();

    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string content = 5;</code>
     */
    java.lang.String getContent();
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string content = 5;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     *附加属性
     * </pre>
     *
     * <code>string property = 6;</code>
     */
    java.lang.String getProperty();
    /**
     * <pre>
     *附加属性
     * </pre>
     *
     * <code>string property = 6;</code>
     */
    com.google.protobuf.ByteString
        getPropertyBytes();
  }
  /**
   * <pre>
   *消息类
   * </pre>
   *
   * Protobuf type {@code MessageRequest}
   */
  public  static final class MessageRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MessageRequest)
      MessageRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageRequest.newBuilder() to construct.
    private MessageRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageRequest() {
      messageFrom_ = "";
      content_ = "";
      property_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              messageId_ = input.readUInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              messageFrom_ = s;
              break;
            }
            case 24: {

              time_ = input.readUInt64();
              break;
            }
            case 32: {

              msgType_ = input.readUInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              property_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.geek.rpc.message.ProtoBufMessage.internal_static_MessageRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.geek.rpc.message.ProtoBufMessage.internal_static_MessageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.geek.rpc.message.ProtoBufMessage.MessageRequest.class, com.geek.rpc.message.ProtoBufMessage.MessageRequest.Builder.class);
    }

    public static final int MESSAGE_ID_FIELD_NUMBER = 1;
    private long messageId_;
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>uint64 message_id = 1;</code>
     */
    public long getMessageId() {
      return messageId_;
    }

    public static final int MESSAGE_FROM_FIELD_NUMBER = 2;
    private volatile java.lang.Object messageFrom_;
    /**
     * <pre>
     *发送方信息
     * </pre>
     *
     * <code>string message_from = 2;</code>
     */
    public java.lang.String getMessageFrom() {
      java.lang.Object ref = messageFrom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageFrom_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *发送方信息
     * </pre>
     *
     * <code>string message_from = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageFromBytes() {
      java.lang.Object ref = messageFrom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageFrom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 3;
    private long time_;
    /**
     * <pre>
     *时间戳(单位:毫秒)
     * </pre>
     *
     * <code>uint64 time = 3;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int MSG_TYPE_FIELD_NUMBER = 4;
    private int msgType_;
    /**
     * <pre>
     *消息类型  1：纯文本  2：其他
     * </pre>
     *
     * <code>uint32 msg_type = 4;</code>
     */
    public int getMsgType() {
      return msgType_;
    }

    public static final int CONTENT_FIELD_NUMBER = 5;
    private volatile java.lang.Object content_;
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string content = 5;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string content = 5;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROPERTY_FIELD_NUMBER = 6;
    private volatile java.lang.Object property_;
    /**
     * <pre>
     *附加属性
     * </pre>
     *
     * <code>string property = 6;</code>
     */
    public java.lang.String getProperty() {
      java.lang.Object ref = property_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        property_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *附加属性
     * </pre>
     *
     * <code>string property = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPropertyBytes() {
      java.lang.Object ref = property_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        property_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageId_ != 0L) {
        output.writeUInt64(1, messageId_);
      }
      if (!getMessageFromBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, messageFrom_);
      }
      if (time_ != 0L) {
        output.writeUInt64(3, time_);
      }
      if (msgType_ != 0) {
        output.writeUInt32(4, msgType_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, content_);
      }
      if (!getPropertyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, property_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, messageId_);
      }
      if (!getMessageFromBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, messageFrom_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, time_);
      }
      if (msgType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, msgType_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, content_);
      }
      if (!getPropertyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, property_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.geek.rpc.message.ProtoBufMessage.MessageRequest)) {
        return super.equals(obj);
      }
      com.geek.rpc.message.ProtoBufMessage.MessageRequest other = (com.geek.rpc.message.ProtoBufMessage.MessageRequest) obj;

      if (getMessageId()
          != other.getMessageId()) return false;
      if (!getMessageFrom()
          .equals(other.getMessageFrom())) return false;
      if (getTime()
          != other.getTime()) return false;
      if (getMsgType()
          != other.getMsgType()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!getProperty()
          .equals(other.getProperty())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGE_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMessageId());
      hash = (37 * hash) + MESSAGE_FROM_FIELD_NUMBER;
      hash = (53 * hash) + getMessageFrom().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + MSG_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgType();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + PROPERTY_FIELD_NUMBER;
      hash = (53 * hash) + getProperty().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.geek.rpc.message.ProtoBufMessage.MessageRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.geek.rpc.message.ProtoBufMessage.MessageRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.geek.rpc.message.ProtoBufMessage.MessageRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.geek.rpc.message.ProtoBufMessage.MessageRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.geek.rpc.message.ProtoBufMessage.MessageRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.geek.rpc.message.ProtoBufMessage.MessageRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.geek.rpc.message.ProtoBufMessage.MessageRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.geek.rpc.message.ProtoBufMessage.MessageRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.geek.rpc.message.ProtoBufMessage.MessageRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.geek.rpc.message.ProtoBufMessage.MessageRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.geek.rpc.message.ProtoBufMessage.MessageRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.geek.rpc.message.ProtoBufMessage.MessageRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.geek.rpc.message.ProtoBufMessage.MessageRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *消息类
     * </pre>
     *
     * Protobuf type {@code MessageRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MessageRequest)
        com.geek.rpc.message.ProtoBufMessage.MessageRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.geek.rpc.message.ProtoBufMessage.internal_static_MessageRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.geek.rpc.message.ProtoBufMessage.internal_static_MessageRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.geek.rpc.message.ProtoBufMessage.MessageRequest.class, com.geek.rpc.message.ProtoBufMessage.MessageRequest.Builder.class);
      }

      // Construct using com.geek.rpc.message.ProtoBufMessage.MessageRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        messageId_ = 0L;

        messageFrom_ = "";

        time_ = 0L;

        msgType_ = 0;

        content_ = "";

        property_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.geek.rpc.message.ProtoBufMessage.internal_static_MessageRequest_descriptor;
      }

      @java.lang.Override
      public com.geek.rpc.message.ProtoBufMessage.MessageRequest getDefaultInstanceForType() {
        return com.geek.rpc.message.ProtoBufMessage.MessageRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.geek.rpc.message.ProtoBufMessage.MessageRequest build() {
        com.geek.rpc.message.ProtoBufMessage.MessageRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.geek.rpc.message.ProtoBufMessage.MessageRequest buildPartial() {
        com.geek.rpc.message.ProtoBufMessage.MessageRequest result = new com.geek.rpc.message.ProtoBufMessage.MessageRequest(this);
        result.messageId_ = messageId_;
        result.messageFrom_ = messageFrom_;
        result.time_ = time_;
        result.msgType_ = msgType_;
        result.content_ = content_;
        result.property_ = property_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.geek.rpc.message.ProtoBufMessage.MessageRequest) {
          return mergeFrom((com.geek.rpc.message.ProtoBufMessage.MessageRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.geek.rpc.message.ProtoBufMessage.MessageRequest other) {
        if (other == com.geek.rpc.message.ProtoBufMessage.MessageRequest.getDefaultInstance()) return this;
        if (other.getMessageId() != 0L) {
          setMessageId(other.getMessageId());
        }
        if (!other.getMessageFrom().isEmpty()) {
          messageFrom_ = other.messageFrom_;
          onChanged();
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (other.getMsgType() != 0) {
          setMsgType(other.getMsgType());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (!other.getProperty().isEmpty()) {
          property_ = other.property_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.geek.rpc.message.ProtoBufMessage.MessageRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.geek.rpc.message.ProtoBufMessage.MessageRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long messageId_ ;
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>uint64 message_id = 1;</code>
       */
      public long getMessageId() {
        return messageId_;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>uint64 message_id = 1;</code>
       */
      public Builder setMessageId(long value) {
        
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>uint64 message_id = 1;</code>
       */
      public Builder clearMessageId() {
        
        messageId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object messageFrom_ = "";
      /**
       * <pre>
       *发送方信息
       * </pre>
       *
       * <code>string message_from = 2;</code>
       */
      public java.lang.String getMessageFrom() {
        java.lang.Object ref = messageFrom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageFrom_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *发送方信息
       * </pre>
       *
       * <code>string message_from = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageFromBytes() {
        java.lang.Object ref = messageFrom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageFrom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发送方信息
       * </pre>
       *
       * <code>string message_from = 2;</code>
       */
      public Builder setMessageFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送方信息
       * </pre>
       *
       * <code>string message_from = 2;</code>
       */
      public Builder clearMessageFrom() {
        
        messageFrom_ = getDefaultInstance().getMessageFrom();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送方信息
       * </pre>
       *
       * <code>string message_from = 2;</code>
       */
      public Builder setMessageFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageFrom_ = value;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <pre>
       *时间戳(单位:毫秒)
       * </pre>
       *
       * <code>uint64 time = 3;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <pre>
       *时间戳(单位:毫秒)
       * </pre>
       *
       * <code>uint64 time = 3;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间戳(单位:毫秒)
       * </pre>
       *
       * <code>uint64 time = 3;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private int msgType_ ;
      /**
       * <pre>
       *消息类型  1：纯文本  2：其他
       * </pre>
       *
       * <code>uint32 msg_type = 4;</code>
       */
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <pre>
       *消息类型  1：纯文本  2：其他
       * </pre>
       *
       * <code>uint32 msg_type = 4;</code>
       */
      public Builder setMsgType(int value) {
        
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型  1：纯文本  2：其他
       * </pre>
       *
       * <code>uint32 msg_type = 4;</code>
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 5;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 5;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 5;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 5;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 5;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object property_ = "";
      /**
       * <pre>
       *附加属性
       * </pre>
       *
       * <code>string property = 6;</code>
       */
      public java.lang.String getProperty() {
        java.lang.Object ref = property_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          property_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *附加属性
       * </pre>
       *
       * <code>string property = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPropertyBytes() {
        java.lang.Object ref = property_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          property_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *附加属性
       * </pre>
       *
       * <code>string property = 6;</code>
       */
      public Builder setProperty(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        property_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *附加属性
       * </pre>
       *
       * <code>string property = 6;</code>
       */
      public Builder clearProperty() {
        
        property_ = getDefaultInstance().getProperty();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *附加属性
       * </pre>
       *
       * <code>string property = 6;</code>
       */
      public Builder setPropertyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        property_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MessageRequest)
    }

    // @@protoc_insertion_point(class_scope:MessageRequest)
    private static final com.geek.rpc.message.ProtoBufMessage.MessageRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.geek.rpc.message.ProtoBufMessage.MessageRequest();
    }

    public static com.geek.rpc.message.ProtoBufMessage.MessageRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageRequest>
        PARSER = new com.google.protobuf.AbstractParser<MessageRequest>() {
      @java.lang.Override
      public MessageRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.geek.rpc.message.ProtoBufMessage.MessageRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027resources/Message.proto\"}\n\016MessageRequ" +
      "est\022\022\n\nmessage_id\030\001 \001(\004\022\024\n\014message_from\030" +
      "\002 \001(\t\022\014\n\004time\030\003 \001(\004\022\020\n\010msg_type\030\004 \001(\r\022\017\n" +
      "\007content\030\005 \001(\t\022\020\n\010property\030\006 \001(\tB\'\n\024com." +
      "geek.rpc.messageB\017ProtoBufMessageb\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageRequest_descriptor,
        new java.lang.String[] { "MessageId", "MessageFrom", "Time", "MsgType", "Content", "Property", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
